### ISSUE TITLE
Store repositories as hashes

### ISSUE THREAD

**Issue by bkcsoft** [sourcepods/sourcepods#38]
TL;DR; instead of storing the repos under `storage/{username}/{reponame}` we should have a on-create-time immutable (not possible in cockroach I know...) name that we use instead.

For example `hashAlgo({username}/{reponame}-{creation_time})` should suffice. Then on disk we'd go e.g. `storage/{hash[:2]}/{hash[2:2]}/{hash[4:]}` (if my array-math checks out...)

Why?
- No need to rename on platter when renaming a repo, or moving to another "group"/namespace. Just a DB-call and we're done.

**Comment by metalmatze** [comment]
Especially when renaming this starts to make a lot of sense. Thanks for pointing out.
I guess we need to do a lookup for the repository in the database anyway, before every call to storage. Therefore we could simply use a UUID generated by the database. Maybe even using the UUID, which is the unique ID, of the repository is suffient.

**Comment by metalmatze** [comment]
Thinking about it a bit more. As we might want to rename repositories but still have the option to redirect requests, it might make sense to simply have a repository-storage table that repositories can reference. Otherwise we still have a tightly coupled repository to storage relationship.

**Comment by bkcsoft** [comment]
> have the option to redirect requests, it might make sense to simply have a repository-storage table that repositories can reference.

That makes sense :+1:

**Comment by tboerger** [comment]
Also if we keep object storage in mind it makes sense to use something like a uuid to get it properly sharded. This post explains it imho pretty well: https://news.ycombinator.com/item?id=16631981

**Comment by metalmatze** [comment]
That sounds like we should use https://github.com/oklog/ulid then. I know that this is what Thanos (and even Prometheus, not completely sure) for block names. I'll investigate a bit more.
